server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 135780
    url: jdbc:postgresql://localhost:5432/CS209Pro?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8


  freemarker:
    suffix=: .html

mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mapConfig/*.xml
logging:
  level:
    root: info
    com.example.cs209project: debug

